
  "fantasy_content" {
      "-xmlns:yahoo": "http://www.yahooapis.com/v1/base.rng",
      "-xmlns": "http://fantasysports.yahooapis.com/fantasy/v2/base.rng",
      "-xml:lang": "en-US",
      "-yahoo:uri": "http://fantasysports.yahooapis.com/fantasy/v2/league/nfl.l.22351",
      "-time": "13.792991638184ms",
      "-copyright": "Data provided by Yahoo! and STATS, LLC",
      "-refresh_rate": "60",
      "league": {
        "league_key": "390.l.22351",
        "league_id": "22351",
        "name": "Salary Cap Dynasty 2019",
        "url": "https://football.fantasysports.yahoo.com/f1/22351",
        "draft_status": "postdraft",
        "num_teams": "12",
        "edit_key": "16",
        "league_update_timestamp": "1577871056",
        "scoring_type": "head",
        "league_type": "private",
        "renew": "380_34068",
        "iris_group_chat_id": "EWFTYULT45AEXPDOCQXVOC55XQ",
        "allow_add_to_dl_extra_pos": "0",
        "is_pro_league": "0",
        "is_cash_league": "0",
        "current_week": "16",
        "start_week": "1",
        "start_date": "2019-09-05",
        "end_week": "16",
        "end_date": "2019-12-23",
        "is_finished": "1",
        "game_code": "nfl",
        "season": "2019"
    }
  }